In [2]:
import pandas as pd

#### Data exploration - why does the 1D model have higher AUC than the 3D model, for logistic regression?

In [3]:
d1 = pd.read_csv("../data/results/false_positive_csv/Proximity_1d_Logistic_Regression_false_positives.csv")
d3 = pd.read_csv("../data/results/false_positive_csv/Proximity_zeroed_Logistic_Regression_false_positives.csv")
geo = pd.read_csv("../data/results/false_positive_csv/G-score_Logistic_Regression_false_positives.csv")

In [4]:
d1

,drug,gene,variant,confidence,one_letter_mutation,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,...,Nearest_Mutation_Index,G_score,WHO_Adjusted_Position,Proximity_to_R_Conferring_zeroed,binary_confidence,confidence_2023,true_label,model_prediction,correct,correct_str
0,Ethambutol,embB,embB_p.Thr642Ala,2) Assoc w R - Interim,T642A,0.833333,Resistant,642,138.0,504.0,...,296.0,-0.020135,NaN,15.739760,1,2) Assoc w R - Interim,1,0,False,Incorrect
1,Ethionamide,inhA,inhA_p.Ile21Thr,1) Assoc w R,I21T,0.793103,Resistant,21,73.0,94.0,...,94.0,2.970098,NaN,0.000000,1,1) Assoc w R,1,0,False,Incorrect
2,Ethionamide,inhA,inhA_p.Ile21Val,1) Assoc w R,I21V,0.888889,Resistant,21,73.0,94.0,...,94.0,2.970098,NaN,0.000000,1,1) Assoc w R,1,0,False,Incorrect
3,Ethionamide,inhA,inhA_p.Ser94Ala,1) Assoc w R,S94A,0.862069,Resistant,94,73.0,21.0,...,21.0,2.393463,NaN,4.253260,1,1) Assoc w R,1,0,False,Incorrect
4,Ethionamide,inhA,inhA_p.Ile194Thr,1) Assoc w R,I194T,0.942308,Resistant,194,45.0,239.0,...,21.0,1.683902,NaN,4.411411,1,1) Assoc w R,1,0,False,Incorrect
5,Ethionamide,inhA,inhA_p.Ala239Val,2) Assoc w R - Interim,A239V,1.000000,Resistant,239,45.0,194.0,...,21.0,1.437975,NaN,4.988499,1,2) Assoc w R - Interim,1,0,False,Incorrect
6,Isoniazid,katG,katG_p.Pro232Ala,2) Assoc w R - Interim,P232A,1.000000,Resistant,232,25.0,257.0,...,315.0,2.620020,NaN,0.000000,1,2) Assoc w R - Interim,1,0,False,Incorrect
7,Isoniazid,katG,katG_p.Pro232Ser,2) Assoc w R - Interim,P232S,1.000000,Resistant,232,25.0,257.0,...,315.0,2.620020,NaN,0.000000,1,2) Assoc w R - Interim,1,0,False,Incorrect
8,Isoniazid,katG,katG_p.Met257Ile,2) Assoc w R - Interim,M257I,0.875000,Resistant,257,22.0,279.0,...,110.0,-0.023108,NaN,7.792862,1,2) Assoc w R - Interim,1,0,False,Incorrect
9,Isoniazid,katG,katG_p.Ser457Gly,4) Not assoc w R - Interim,S457G,0.000000,Susceptible,457,4.0,461.0,...,461.0,-0.425378,NaN,3.110083,0,4) Not assoc w R - Interim,0,1,False,Incorrect
10,Streptomycin,gid,gid_p.Leu91Val,4) Not assoc w R - Interim,L91V,0.857143,Susceptible,91,1.0,90.0,...,90.0,2.577261,NaN,0.000000,0,4) Not assoc w R - Interim,0,1,False,Incorrect
11,Streptomycin,gid,gid_p.Ala205Thr,5) Not assoc w R,A205T,0.138889,Susceptible,205,5.0,200.0,...,146.0,-1.511881,NaN,5.070793,0,5) Not assoc w R,0,1,False,Incorrect

In [5]:
d3

,drug,gene,variant,confidence,one_letter_mutation,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,...,Nearest_Mutation_Index,G_score,WHO_Adjusted_Position,Proximity_to_R_Conferring_zeroed,binary_confidence,confidence_2023,true_label,model_prediction,correct,correct_str
0,Bedaquiline,Rv0678,Rv0678_p.Leu32Ser,1) Assoc w R,L32S,1.000000,Resistant,32,4.0,36.0,...,36.0,-0.863333,NaN,5.598959,1,1) Assoc w R,1,0,False,Incorrect
1,Ethambutol,embB,embB_p.Val456Ala,1) Assoc w R,V456A,0.904762,Resistant,456,11.0,445.0,...,445.0,0.131988,NaN,16.113940,1,1) Assoc w R,1,0,False,Incorrect
2,Ethambutol,embB,embB_p.Thr642Ala,2) Assoc w R - Interim,T642A,0.833333,Resistant,642,138.0,504.0,...,296.0,-0.020135,NaN,15.739760,1,2) Assoc w R - Interim,1,0,False,Incorrect
3,Ethionamide,ethA,ethA_p.Thr321Pro,1) Assoc w R,T321P,1.000000,Resistant,321,7.0,314.0,...,205.0,-1.661203,NaN,10.297887,1,1) Assoc w R,1,0,False,Incorrect
4,Isoniazid,katG,katG_p.Met257Ile,2) Assoc w R - Interim,M257I,0.875000,Resistant,257,22.0,279.0,...,110.0,-0.023108,NaN,7.792862,1,2) Assoc w R - Interim,1,0,False,Incorrect
5,Isoniazid,katG,katG_p.Ser457Gly,4) Not assoc w R - Interim,S457G,0.000000,Susceptible,457,4.0,461.0,...,461.0,-0.425378,NaN,3.110083,0,4) Not assoc w R - Interim,0,1,False,Incorrect
6,Levofloxacin,gyrA,gyrA_p.Ala74Ser,2) Assoc w R - Interim,A74S,0.750000,Resistant,74,4.0,70.0,...,89.0,1.804813,NaN,7.600666,1,2) Assoc w R - Interim,1,0,False,Incorrect
7,Streptomycin,gid,gid_p.Leu91Val,4) Not assoc w R - Interim,L91V,0.857143,Susceptible,91,1.0,90.0,...,90.0,2.577261,NaN,0.000000,0,4) Not assoc w R - Interim,0,1,False,Incorrect
8,Streptomycin,gid,gid_p.Val124Ala,2) Assoc w R - Interim,V124A,0.666667,Resistant,124,5.0,119.0,...,119.0,-0.639265,NaN,5.139420,1,2) Assoc w R - Interim,1,0,False,Incorrect

In [6]:
len(d1), len(d3)

(12, 9)

In [8]:
inner = d1.merge(d3["variant"], on="variant", how="inner")
display_columns = [ 'gene', 'variant', 'confidence',
       'frequency', 'phenotype', 'position', 'Proximity_1D',
       'Nearest_1D_Index', 'Proximity_to_R_Conferring',
       'Nearest_Mutation_Index', 'G_score']
inner[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
0,embB,embB_p.Thr642Ala,2) Assoc w R - Interim,0.833333,Resistant,642,138.0,504.0,15.739760,296.0,-0.020135
1,katG,katG_p.Met257Ile,2) Assoc w R - Interim,0.875000,Resistant,257,22.0,279.0,7.792862,110.0,-0.023108
2,katG,katG_p.Ser457Gly,4) Not assoc w R - Interim,0.000000,Susceptible,457,4.0,461.0,3.110083,461.0,-0.425378
3,gid,gid_p.Leu91Val,4) Not assoc w R - Interim,0.857143,Susceptible,91,1.0,90.0,1.328856,90.0,2.577261

In [9]:
d3_variants = list(d3.variant)
d1_only = d1.query("variant not in @d3_variants")
d1_only[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
1,inhA,inhA_p.Ile21Thr,1) Assoc w R,0.793103,Resistant,21,73.0,94.0,4.253260,94.0,2.970098
2,inhA,inhA_p.Ile21Val,1) Assoc w R,0.888889,Resistant,21,73.0,94.0,4.253260,94.0,2.970098
3,inhA,inhA_p.Ser94Ala,1) Assoc w R,0.862069,Resistant,94,73.0,21.0,4.253260,21.0,2.393463
4,inhA,inhA_p.Ile194Thr,1) Assoc w R,0.942308,Resistant,194,45.0,239.0,4.411411,21.0,1.683902
5,inhA,inhA_p.Ala239Val,2) Assoc w R - Interim,1.000000,Resistant,239,45.0,194.0,4.988499,21.0,1.437975
6,katG,katG_p.Pro232Ala,2) Assoc w R - Interim,1.000000,Resistant,232,25.0,257.0,5.579781,315.0,2.620020
7,katG,katG_p.Pro232Ser,2) Assoc w R - Interim,1.000000,Resistant,232,25.0,257.0,5.579781,315.0,2.620020
11,gid,gid_p.Ala205Thr,5) Not assoc w R,0.138889,Susceptible,205,5.0,200.0,5.070793,146.0,-1.511881

In [12]:
inner = geo.merge(d3["variant"], on="variant", how="inner")
display_columns = [ 'gene', 'variant', 'confidence',
       'frequency', 'phenotype', 'position', 'Proximity_1D',
       'Nearest_1D_Index', 'Proximity_to_R_Conferring',
       'Nearest_Mutation_Index', 'G_score']
inner[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
0,Rv0678,Rv0678_p.Leu32Ser,1) Assoc w R,1.000000,Resistant,32,4.0,36.0,5.598959,36.0,-0.863333
1,embB,embB_p.Val456Ala,1) Assoc w R,0.904762,Resistant,456,11.0,445.0,16.113940,445.0,0.131988
2,embB,embB_p.Thr642Ala,2) Assoc w R - Interim,0.833333,Resistant,642,138.0,504.0,15.739760,296.0,-0.020135
3,ethA,ethA_p.Thr321Pro,1) Assoc w R,1.000000,Resistant,321,7.0,314.0,10.297887,205.0,-1.661203
4,katG,katG_p.Met257Ile,2) Assoc w R - Interim,0.875000,Resistant,257,22.0,279.0,7.792862,110.0,-0.023108
5,gid,gid_p.Leu91Val,4) Not assoc w R - Interim,0.857143,Susceptible,91,1.0,90.0,1.328856,90.0,2.577261
6,gid,gid_p.Val124Ala,2) Assoc w R - Interim,0.666667,Resistant,124,5.0,119.0,5.139420,119.0,-0.639265

In [13]:
d3_variants = list(d3.variant)
geo_only = geo.query("variant not in @d3_variants")
geo_only[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
1,Rv0678,Rv0678_p.Ala36Val,2) Assoc w R - Interim,1.000000,Resistant,36,4.0,32.0,3.462852,70.0,-0.678176
2,Rv0678,Rv0678_p.Ile67Ser,2) Assoc w R - Interim,1.000000,Resistant,67,3.0,70.0,3.490235,70.0,-0.925103
3,Rv0678,Rv0678_p.Met146Thr,2) Assoc w R - Interim,0.000000,Resistant,146,4.0,142.0,2.870637,142.0,-0.455283
4,embB,embB_p.Ser347Ile,1) Assoc w R,0.684211,Resistant,347,7.0,354.0,4.549995,296.0,0.968332
5,embB,embB_p.Ser347Thr,1) Assoc w R,0.833333,Resistant,347,7.0,354.0,4.549995,296.0,0.968332
8,ethA,ethA_p.Leu194Pro,2) Assoc w R - Interim,1.000000,Resistant,194,8.0,202.0,3.898033,202.0,0.700413
9,ethA,ethA_p.Val202Gly,2) Assoc w R - Interim,1.000000,Resistant,202,3.0,205.0,3.898033,194.0,-0.273270
11,ethA,ethA_p.Ala381Pro,2) Assoc w R - Interim,1.000000,Resistant,381,2.0,379.0,4.373444,379.0,0.567400
12,katG,katG_p.Ala109Val,1) Assoc w R,1.000000,Resistant,109,1.0,110.0,1.324344,110.0,0.446090
13,katG,katG_p.Ala110Val,1) Assoc w R,1.000000,Resistant,110,1.0,109.0,1.324344,109.0,0.244966
15,katG,katG_p.Gly297Val,1) Assoc w R,0.857143,Resistant,297,2.0,299.0,4.123461,299.0,0.549738
16,katG,katG_p.Gly299Ser,2) Assoc w R - Interim,1.000000,Resistant,299,2.0,297.0,3.066974,142.0,0.996816
17,pncA,pncA_p.Leu35Pro,1) Assoc w R,0.625000,Resistant,35,1.0,34.0,1.317835,34.0,-0.961242
18,pncA,pncA_p.His43Pro,1) Assoc w R,1.000000,Resistant,43,1.0,44.0,1.343585,44.0,-1.023458
19,pncA,pncA_p.Pro54Ser,1) Assoc w R,1.000000,Resistant,54,3.0,51.0,3.276495,57.0,1.006284
20,pncA,pncA_p.Thr114Pro,1) Assoc w R,1.000000,Resistant,114,2.0,116.0,3.408113,94.0,-1.166240
21,pncA,pncA_p.Leu156Pro,1) Assoc w R,1.000000,Resistant,156,1.0,155.0,1.337633,155.0,0.271429
22,pncA,pncA_p.Leu159Pro,1) Assoc w R,1.000000,Resistant,159,1.0,160.0,1.326588,160.0,0.390724
23,pncA,pncA_p.Leu159Val,1) Assoc w R,0.750000,Resistant,159,1.0,160.0,1.326588,160.0,0.390724
24,pncA,pncA_p.Met175Ile,1) Assoc w R,0.500000,Resistant,175,2.0,177.0,2.990264,171.0,0.215259
27,gid,gid_p.Leu152Ser,2) Assoc w R - Interim,1.000000,Resistant,152,3.0,149.0,2.980505,149.0,-0.522283

In [11]:
### repeating the examination for the 1D + GeO and 3D + GeO

In [51]:
d1 = pd.read_csv("../data/results/false_positive_csv/G-score_+_Proximity_1D_Logistic_Regression_false_positives.csv")
d3 = pd.read_csv("../data/results/false_positive_csv/G-score_+_Proximity_3D_zeroed_Logistic_Regression_false_positives.csv")

In [52]:
d1[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
0,embB,embB_T642A,2) Assoc w R - Interim,0.833333,Resistant,642,138.0,504.0,15.739760,296.0,-0.020135
1,inhA,inhA_I21T,1) Assoc w R,0.793103,Resistant,21,73.0,94.0,4.253260,94.0,2.970098
2,inhA,inhA_I21V,1) Assoc w R,0.888889,Resistant,21,73.0,94.0,4.253260,94.0,2.970098
3,inhA,inhA_S94A,1) Assoc w R,0.862069,Resistant,94,73.0,21.0,4.253260,21.0,2.393463
4,inhA,inhA_I194T,1) Assoc w R,0.942308,Resistant,194,45.0,239.0,4.411411,21.0,1.683902
5,inhA,inhA_A239V,2) Assoc w R - Interim,1.000000,Resistant,239,45.0,194.0,4.988499,21.0,1.437975
6,katG,katG_P232A,2) Assoc w R - Interim,1.000000,Resistant,232,25.0,257.0,5.579781,315.0,2.620020
7,katG,katG_P232S,2) Assoc w R - Interim,1.000000,Resistant,232,25.0,257.0,5.579781,315.0,2.620020
8,katG,katG_M257I,2) Assoc w R - Interim,0.875000,Resistant,257,22.0,279.0,7.792862,110.0,-0.023108
9,katG,katG_S457G,4) Not assoc w R - Interim,0.000000,Susceptible,457,4.0,461.0,3.110083,461.0,-0.425378
10,gid,gid_L91V,4) Not assoc w R - Interim,0.857143,Susceptible,91,1.0,90.0,1.328856,90.0,2.577261
11,gid,gid_A205T,5) Not assoc w R,0.138889,Susceptible,205,5.0,200.0,5.070793,146.0,-1.511881

In [53]:
d3[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
0,Rv0678,Rv0678_L32S,1) Assoc w R,1.000000,Resistant,32,4.0,36.0,5.598959,36.0,-0.863333
1,embB,embB_V456A,1) Assoc w R,0.904762,Resistant,456,11.0,445.0,16.113940,445.0,0.131988
2,embB,embB_T642A,2) Assoc w R - Interim,0.833333,Resistant,642,138.0,504.0,15.739760,296.0,-0.020135
3,ethA,ethA_T321P,1) Assoc w R,1.000000,Resistant,321,7.0,314.0,10.297887,205.0,-1.661203
4,katG,katG_M257I,2) Assoc w R - Interim,0.875000,Resistant,257,22.0,279.0,7.792862,110.0,-0.023108
5,katG,katG_S457G,4) Not assoc w R - Interim,0.000000,Susceptible,457,4.0,461.0,3.110083,461.0,-0.425378
6,gyrA,gyrA_A74S,2) Assoc w R - Interim,0.750000,Resistant,74,4.0,70.0,7.600666,89.0,1.804813
7,gid,gid_L91V,4) Not assoc w R - Interim,0.857143,Susceptible,91,1.0,90.0,1.328856,90.0,2.577261
8,gid,gid_V124A,2) Assoc w R - Interim,0.666667,Resistant,124,5.0,119.0,5.139420,119.0,-0.639265

In [54]:
inner = d1.merge(d3["variant"], on="variant", how="inner")
#display_columns = [ 'gene', 'variant', 'confidence',
#
inner[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
0,embB,embB_T642A,2) Assoc w R - Interim,0.833333,Resistant,642,138.0,504.0,15.739760,296.0,-0.020135
1,katG,katG_M257I,2) Assoc w R - Interim,0.875000,Resistant,257,22.0,279.0,7.792862,110.0,-0.023108
2,katG,katG_S457G,4) Not assoc w R - Interim,0.000000,Susceptible,457,4.0,461.0,3.110083,461.0,-0.425378
3,gid,gid_L91V,4) Not assoc w R - Interim,0.857143,Susceptible,91,1.0,90.0,1.328856,90.0,2.577261

In [55]:
print(len(d1), len(d3), len(inner))

12 9 4

In [56]:
d3_variants = list(d3.variant)
d1_only = d1.query("variant not in @d3_variants")
d1_only[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
1,inhA,inhA_I21T,1) Assoc w R,0.793103,Resistant,21,73.0,94.0,4.253260,94.0,2.970098
2,inhA,inhA_I21V,1) Assoc w R,0.888889,Resistant,21,73.0,94.0,4.253260,94.0,2.970098
3,inhA,inhA_S94A,1) Assoc w R,0.862069,Resistant,94,73.0,21.0,4.253260,21.0,2.393463
4,inhA,inhA_I194T,1) Assoc w R,0.942308,Resistant,194,45.0,239.0,4.411411,21.0,1.683902
5,inhA,inhA_A239V,2) Assoc w R - Interim,1.000000,Resistant,239,45.0,194.0,4.988499,21.0,1.437975
6,katG,katG_P232A,2) Assoc w R - Interim,1.000000,Resistant,232,25.0,257.0,5.579781,315.0,2.620020
7,katG,katG_P232S,2) Assoc w R - Interim,1.000000,Resistant,232,25.0,257.0,5.579781,315.0,2.620020
11,gid,gid_A205T,5) Not assoc w R,0.138889,Susceptible,205,5.0,200.0,5.070793,146.0,-1.511881

In [57]:
d1_variants = list(d1.variant)
d3_only = d3.query("variant not in @d1_variants")
d3_only[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
0,Rv0678,Rv0678_L32S,1) Assoc w R,1.000000,Resistant,32,4.0,36.0,5.598959,36.0,-0.863333
1,embB,embB_V456A,1) Assoc w R,0.904762,Resistant,456,11.0,445.0,16.113940,445.0,0.131988
3,ethA,ethA_T321P,1) Assoc w R,1.000000,Resistant,321,7.0,314.0,10.297887,205.0,-1.661203
6,gyrA,gyrA_A74S,2) Assoc w R - Interim,0.750000,Resistant,74,4.0,70.0,7.600666,89.0,1.804813
8,gid,gid_V124A,2) Assoc w R - Interim,0.666667,Resistant,124,5.0,119.0,5.139420,119.0,-0.639265

In [59]:
d3[display_columns]

,gene,variant,confidence,frequency,phenotype,position,Proximity_1D,Nearest_1D_Index,Proximity_to_R_Conferring,Nearest_Mutation_Index,G_score
0,Rv0678,Rv0678_L32S,1) Assoc w R,1.000000,Resistant,32,4.0,36.0,5.598959,36.0,-0.863333
1,embB,embB_V456A,1) Assoc w R,0.904762,Resistant,456,11.0,445.0,16.113940,445.0,0.131988
2,embB,embB_T642A,2) Assoc w R - Interim,0.833333,Resistant,642,138.0,504.0,15.739760,296.0,-0.020135
3,ethA,ethA_T321P,1) Assoc w R,1.000000,Resistant,321,7.0,314.0,10.297887,205.0,-1.661203
4,katG,katG_M257I,2) Assoc w R - Interim,0.875000,Resistant,257,22.0,279.0,7.792862,110.0,-0.023108
5,katG,katG_S457G,4) Not assoc w R - Interim,0.000000,Susceptible,457,4.0,461.0,3.110083,461.0,-0.425378
6,gyrA,gyrA_A74S,2) Assoc w R - Interim,0.750000,Resistant,74,4.0,70.0,7.600666,89.0,1.804813
7,gid,gid_L91V,4) Not assoc w R - Interim,0.857143,Susceptible,91,1.0,90.0,1.328856,90.0,2.577261
8,gid,gid_V124A,2) Assoc w R - Interim,0.666667,Resistant,124,5.0,119.0,5.139420,119.0,-0.639265